### ISSUE TITLE
Enable client specific JTAC message repeat

### ISSUE THREAD

**Issue by red15** [afinegan/DynamicDCS#25]
Enable client specific JTAC message repeat (not sure if possible for client/side/at all)

Source: #todo mad rabbit#9249

**Comment by red15** [comment]
Not sure if this is worth the hassle, the implementation might be quite difficult, having to store all spots in the DB so they can be repeated when the client would ask for it (via F10 or something).

Also it removes a bit of gameplay by not forcing the players to communicate to keep track of targets. There is also already a big red/blue plume on top (or nearby) it so it shouldn't be that hard.

**Comment by mangos64** [comment]
Could use a custom radio freq for constant Jtac messages. although that may require in mission scripting.

**Comment by red15** [comment]
Using in-game audio is not a scalable method, it would increase the mission size exponentially and does not really solve the complexity involved in this request. Perhaps we need to find out more about why the current repeat frequency is a problem. Is it to obtain more of a global picture of what is happening on which fronts? Perhaps implementing a sort of "PICTURE" like from the awacs should be able to alleviate this? Where reports are condensed to: "2 in MM37, 1 in MN35" etc?

**Comment by dwendelen** [comment]
What about showing the message longer

**Comment by mangos64** [comment]
@red15 Not using ingame audio just a frequency that you are switched too that enables constant jtac messages to be displayed. No audio involved. But yes f10 option would be better

**Comment by afinegan** [comment]
This is the data of what I keep per unit, I don't know of a way to find out the units radio settings
`{ 
    "_id" : "Maykop-Khanskaya #6071300", 
    "playerCanDrive" : false, 
    "hidden" : false, 
    "enabled" : true, 
    "dead" : false, 
    "isTroop" : false, 
    "isCrate" : false, 
    "isCombo" : false, 
    "isResync" : true, 
    "isAI" : false, 
    "ammo" : [

    ], 
    "agl" : NumberInt(0), 
    "alt" : 180.01019287109, 
    "category" : "GROUND", 
    "coalition" : NumberInt(2), 
    "country" : "USA", 
    "groupId" : NumberInt(1001225), 
    "groupName" : "Maykop-Khanskaya #6071299", 
    "hdg" : NumberInt(355), 
    "inAir" : false, 
    "lonLatLoc" : [
        40.02834794733, 
        44.678335512994
    ], 
    "name" : "Maykop-Khanskaya #6071300", 
    "playername" : "", 
    "speed" : NumberInt(0), 
    "type" : "Leopard-2", 
    "unitId" : NumberInt(1001226), 
    "createdAt" : ISODate("2019-06-16T20:05:22.289+0000"), 
    "updatedAt" : ISODate("2019-06-17T01:26:22.663+0000"), 
    "__v" : NumberInt(0)
}
`

**Comment by red15** [comment]
You're right that is the basic unit info, you'll need to talk to its controller to get the task information

https://wiki.hoggitworld.com/view/DCS_Class_Controller

**Comment by red15** [comment]
> What about showing the message longer

That's not a solution either, how long is long enough for everyone, also it could provide more clutter on the screen if a lot of JTAC's are active. Some people will then complain about the message being there too long.
