### ISSUE TITLE
DDCS Persian Gulf Modern v.3.28 Testing & Feedback from mad rabbit

### ISSUE THREAD

**Issue by madrabbit711** [afinegan/DynamicDCS#30]
**DDCS PG Modern v.3.28 (Spring) Testing**

**Legend:**
? queries/suggestions
[1] / [2] / [3] minor/moderate/major problems

**Things I looked for:**
- Helos spawns close to static objects preventing taxke-off, on uneven terrain = potential minor damage amplified with desync
- Airplane spawns that allow enough room to taxi
- Cargo plane spawns that allow internal cargo to be picked-up without taxxing

**Some odd things observed that can most likely be ignored**
- Mig21 has a roughs spawn at times but doesn't seem damaged
- L39 will spawn with remnant engine sound that dissapates at some airports

**PRE-EXISTING BUGS**
- [1] Infantry able to be deployed within FOB radius i.e. MANPADs next to CC
- [1] Strela-10 still not firing (flew right over one I slung with a Hornet really slow, several times).  Need to test Avenger and Linebacker.

**OVERALL**
- ? carrier control dependent on which bases?  Available to one team only when required bases captured? Need in briefing
- ? Web map ownership icons for carriers
- ? Web map base names especially for those new to PG
- ? LP system graphics to briefing
- ? consider placing FARP pad next to roads at FOBs with flat very flat terrain to allow Viggen reloading
- ? All MOBS spawn helos on FARP helipads.  Is this intended?
- [3] No pre-spawned AWACS for either team and no option to spawn them either.
- [3] Red team are able to spawn at Sharjah Intl neutral AB in UAE.  I don't think this is intended, assuming current map represents fresh reset.
- ? Sir Abu Nuayr, Sirri Island, Tunb Island AFB,  Tunb Kochak, Lavan Island are not pre-captured by blue at start but are neutral ABs.  Is this intentional?
- ?? Why are 2 x Frigates and 1 x cruiser docked at Abu Musa Island Airport? What happens to these when Abu Musa Island Airport captured by opposing team during the same session and after restart?
- ??? Fujairah Intl AB, Al Ain Airport and Bandar e-Jask airfields have mission generated markers but not listed as a neutral ABs, nor owned by either team i.e. spawn not capable.  Is this intentional?  The position of these bases as neutral capture seems pretty cruicial to both teams.  Indeed, a friendly unit could be placed on this base and still allow rearming and refueling due to DCS engine (not DDCS server) mechanics.  Therefore, might as well make this a neutral airbase.
- ? More FOBs and MOBs in UAE need, particularly in the centre, east of the West coast
- ? Less FOBs in Iran and more spacing but converted some to MOBs.  This many FOBS requires too much repairing for either team simply for denial, especially with status no longer shown on web map.
- ? Perhaps give blue Bandar e-Jask airfield as well as some FOB leading-up to Bandar Abbas Intl.

**RED TEAM**
- ? Mig29A less capable than Mig29S but at all red air bases. This intended?
- [3] Bandar Abbas 001 F14B is tight fit in hanger and barely able to turn left after exiting hanger due to wall
- [1] BQ58 FOB 000 Mi8 & UH-1H rough spawn = minor damage?.  Not on flat terrain?
- [1] ET80 FOB 000 + 001 KA50 rough spawn (shaky) and too close to steep FARP pad
- [1] ET80 FOB 000 Mi8 rough spawn = minor damage?.  Not on flat terrain?
- [1] EU22 FOB 001 Mi8 shaky spawn =  tremble.  More annyoing than damage concerning
- [1] Jiroft Aiport 000 to 003 AV-8B all face dirt (south) rather than inside of ramp (north) leaving little turning room
- [1] Jiroft Aiport 000 to 003 KA50 slanted (right side sunken) spawn. Rotors very close to hitting ground on right side upon startup
- ? Jiroft Airport: add 2nd L39
- [1] Jiroft Aiport 000 to 003 Mi8 slanted (right side sunken) spawn. Rough for slot 003 = minor damage.
- [1] Kerman Aiport 002, 003 AV-8B all face dirt rather than inside of ramp leaving little turning room
- [1] Kerman Aiport 000, 001 TF-51 not within base radius to pick-up internal crate
- ? Why only 2 YAK-52 for all of red team and only at Kerman and Kish Airport? (not that I care, I don't own it)
- [1] Kish Aiport 000 to 003 KA50 slanted (right side sunken) spawn. Rotors very close to hitting ground on right side upon startup
- [3] Lar Airbase 000, 001 A10C spawn location in isolatd tarmac with no connection to runway and unable to taxi anywhere i.e. unsuable
- [3] Lar Airbase 000 to 003 AV-8B all face dirt and fence (north), with little to no room to turn around even with NWS HI
- [2] Lar Airbase ALL HELO spawn left side a little too close to ONLY runway
- ? Lar Airbase: add 2nd L39
- [1] Qeshm Island 000 Mi8 shaky spawn =  tremble.  More annyoing than damage concerning
- [1] Shiraz Int Airport 000, 001 L39 unable to pickup internal crate from initial location as outside base radius (but able to rearm?!)
- [1] Shiraz Int Airport ALL HELO spawn left side a little too close to runway

**BLUE TEAM**
- ? A10A not A10C as some bases.  This intentional?  No A10A at Khasab AB.
- ? Su25T to blue.  This still necessary?
- [2] Beachead  KA50 and UH1H listed as @ Beachead FOB but spawns on Beachead LHA carrier.  This is confusing.
- [3] All blue Mi8 and UH-1H at FOBs spawn on FARP pads c.f. ground.  This is not in-line with red team FOBs and is a potential balancing issue. i.e. 2mins for Huey with mini-guns to be up in the air.
- ? Khasab AB: add 2nd TF-51

**Comment by madrabbit711** [comment]
Related Pre-existing issues to still test:

Repair not prevented on contested bases (includes FOBs, MOB and ABs)
https://github.com/afinegan/DynamicDCS_BugReports/issues/30
https://github.com/afinegan/DynamicDCS_BugReports/issues/23

**Comment by gunnarmarine** [comment]
> ? carrier control dependent on which bases? Available to one team only when required bases 

Dependant on the ownership of the Beachead FOB and Abu Musa Island

> Web map ownership icons for carriers
> ? Web map base names especially for those new to PG
> ? LP system graphics to briefing

still working on the small things

> ? consider placing FARP pad next to roads at FOBs with flat very flat terrain to allow Viggen reloading

I didn't have time to fine tune their placements for the road. Will be adjusted later.

> ? All MOBS spawn helos on FARP helipads. Is this intended?

yes

> [3] No pre-spawned AWACS for either team and no option to spawn them either.

We are planning to test the spawnable awacs before PG is open to the public.

> [3] Red team are able to spawn at Sharjah Intl neutral AB in UAE. I don't think this is intended, assuming current map represents fresh reset.

This has already been corrected. soon as it resets it will be fixed.

> ? Sir Abu Nuayr, Sirri Island, Tunb Island AFB, Tunb Kochak, Lavan Island are not pre-captured by blue at start but are neutral ABs. Is this intentional?

Yes I wanted blue and red to have desire to capture them and blue to fly their helicopters from the ships and capture an island

> ?? Why are 2 x Frigates and 1 x cruiser docked at Abu Musa Island Airport? What happens to these when Abu Musa Island Airport captured by opposing team during the same session and after restart?

Abu Musa Island is the trigger for the carrier group. Think of it like a MOB that only works for blue. If red side captures it will act like a simple neutral airfield. It will be a key island to take back for blue if they are pushed out of iran and red invades UAE.

> ??? Fujairah Intl AB, Al Ain Airport and Bandar e-Jask airfields have mission generated markers but not listed as a neutral ABs, nor owned by either team i.e. spawn not capable. Is this intentional? The position of these bases as neutral capture seems pretty cruicial to both teams. Indeed, a friendly unit could be placed on this base and still allow rearming and refueling due to DCS engine (not DDCS server) mechanics. Therefore, might as well make this a neutral airbase.

Some airbases are not used because of distances and their locations within a city. Other airbases like Fujairah is not used because of the close proximity of the main airfields in the region. I believe it would cause great frustration to blue team over the flat terrain.

> ? More FOBs and MOBs in UAE need, particularly in the center, east of the West coast

I'll take a look at it again. I believe at the time I felt it would be too confusing because I would end up making a neutral airfield a MOB and not a full blown active airfield with fixed wing

> ? Less FOBs in Iran and more spacing but converted some to MOBs. This many FOBS requires too much repairing for either team simply for denial, especially with status no longer shown on web map.

could be an option but I was afraid having too many mobs would push the unit count too high and also make it too grindy. after we experience a playthrough we will know for sure if more mobs are needed. 

> ? Perhaps give blue Bandar e-Jask airfield as well as some FOB leading-up to Bandar Abbas Intl.

I wanted to push blue team to use the carriers at reset allowing them to attack iran in several directions.

**Comment by gunnarmarine** [comment]
all bad spawns fixed in that list by rabbit. as of version 2.29

**Comment by madrabbit711** [comment]
> I believe it would cause great frustration to blue team over the flat terrain.
The whole ocean is 'flat terrain'.  The difference being with Fujairah and with perhaps some MOBs/FOBs in-between, some SAMs can be established.

- Watching HARMS at the moment, I don't think the Su25T is warranted on blue, especially with the TGP and MavE/Fs.
- The IR SAMs for red i.e. Strela-10, really need to get working for any map, PG or Cau.  This is a major balancing issue at the moment.
- Are Rolands intercepting missiles again? Need to test.
- I still think the carrier (not the LHA) is way too close to the shore for the beachead.  If that's intended e.g. red artillery barrage from 2 FOBS away, then great but it's vulnerabilities to ground vehicles should be tested much like Quaggles has itemized weapons that kill a CC.  The proximity of the carrier to land also makes the approach of RB15 missiles from the Viggen limited.
- In addition to it being unclear in regards to capture conditions and carrier access, it's also unclear if both teams will have access to the carriers under the same conditions e.g. does red team get the carrier if they get the beachead? Why would they need it there?
